# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 285)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.liftDataLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.liftDataLabel.setText("")
        self.liftDataLabel.setObjectName("liftDataLabel")
        self.horizontalLayout.addWidget(self.liftDataLabel)
        self.liftDataButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.liftDataButton.setObjectName("liftDataButton")
        self.horizontalLayout.addWidget(self.liftDataButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.bodyDataLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.bodyDataLabel.setText("")
        self.bodyDataLabel.setObjectName("bodyDataLabel")
        self.horizontalLayout_2.addWidget(self.bodyDataLabel)
        self.bodyDataButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bodyDataButton.setObjectName("bodyDataButton")
        self.horizontalLayout_2.addWidget(self.bodyDataButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.maxVolBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.maxVolBtn.setObjectName("maxVolBtn")
        self.gridLayout.addWidget(self.maxVolBtn, 1, 0, 1, 1)
        self.recentBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.recentBtn.setObjectName("recentBtn")
        self.gridLayout.addWidget(self.recentBtn, 2, 0, 1, 1)
        self.bodyButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bodyButton.setObjectName("bodyButton")
        self.gridLayout.addWidget(self.bodyButton, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.liftsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.liftsButton.setObjectName("liftsButton")
        self.gridLayout.addWidget(self.liftsButton, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Lift Data"))
        self.liftDataButton.setText(_translate("MainWindow", "Select File"))
        self.label_4.setText(_translate("MainWindow", "Body Data"))
        self.bodyDataButton.setText(_translate("MainWindow", "Select File"))
        self.maxVolBtn.setText(_translate("MainWindow", "Max Volume"))
        self.recentBtn.setText(_translate("MainWindow", "Most Recent"))
        self.bodyButton.setText(_translate("MainWindow", "Body Measurments"))
        self.label_2.setText(_translate("MainWindow", "Graphs"))
        self.label.setText(_translate("MainWindow", "Reports"))
        self.liftsButton.setText(_translate("MainWindow", "Lifts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
