# Form implementation generated from reading ui file 'fit.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 515)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(199, 162, 361, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.latestLiftButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.latestLiftButton_2.setObjectName("latestLiftButton_2")
        self.gridLayout.addWidget(self.latestLiftButton_2, 1, 0, 1, 1)
        self.latestLiftButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.latestLiftButton_3.setObjectName("latestLiftButton_3")
        self.gridLayout.addWidget(self.latestLiftButton_3, 2, 0, 1, 1)
        self.bodyButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.bodyButton.setObjectName("bodyButton")
        self.gridLayout.addWidget(self.bodyButton, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.liftsButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.liftsButton.setObjectName("liftsButton")
        self.gridLayout.addWidget(self.liftsButton, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.latestLiftButton_2.setText(_translate("MainWindow", "Max Volume"))
        self.latestLiftButton_3.setText(_translate("MainWindow", "Most Recent"))
        self.bodyButton.setText(_translate("MainWindow", "Body Measurments"))
        self.label_2.setText(_translate("MainWindow", "Graphs"))
        self.label.setText(_translate("MainWindow", "Reports"))
        self.liftsButton.setText(_translate("MainWindow", "Lifts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
